### ISSUE TITLE
Remove DvCodedString

### ISSUE THREAD

**Issue by twcook** [mlhim/specs#54]
Replace current DvCodedString concepts with DvStrings with enumerations and URLs.

**Comment by wolandscat** [comment]
Hi Tim, we are doing a lot of processing on openEHR RM outstanding PRs at the moment, leading to next releases. Some types like DvIdentifier will change. Would be interesting to know what changes you guys are making and the reasons. This search shows our DV issues being looked at - https://openehr.atlassian.net/issues/?jql=project%20%3D%20SPECPR%20AND%20resolution%20%3D%20Unresolved%20AND%20component%20%3D%20rm.data_types%20ORDER%20BY%20priority%20DESC

Is there a summary of MLHIM changes like this we could look at? Another question is: is there a way to make the next generation openEHR and MLHIM XSDs closer?

thx

**Comment by twcook** [comment]
Hi Tom,

On Thu, May 21, 2015 at 4:15 AM, Thomas Beale <notifications@github.com>
wrote:

> Is there a summary of MLHIM changes like this we could look at?
>

​Each release is available on GitHub and has a changelog of commits.  Some
releases have issues that were closed.
The first versions that include the departure from a strictly openEHR
compliant model are available on Launchpad.  ​

Another question is: is there a way to make the next generation openEHR and
> MLHIM XSDs closer?
>
>
​No. There are major differences in philosophy.  We started at openEHR and
innovated from there.
WE implemented ideas proposed by myself and others to the openEHR
foundation. Then expanded on those changes with further lessons learned.

In openEHR and other approaches (the SDO/top down approach) there is the
idea that consensus can be reached on concept models. In MLHIM we minimized
the RM and developed a way to have bottom up modeling and still maintain
semantic interoperability.  We also incorporated semantic web technologies
to maximize reuse of existing tools and talents.

You can find some of those concepts presented in various SlideShares and
videos on YouTube.
Specifically http://www.slideshare.net/twcook/aehin-2014 (especially
starting at 17)
The companion video: https://youtu.be/O6p_pxH7UVs?t=4m20s

I hope this answers your questions.




============================================
Timothy Cook
LinkedIn Profile:http://www.linkedin.com/in/timothywaynecook
MLHIM http://www.mlhim.org
