### ISSUE TITLE
Minor corrections on 3 pages of documentation

### ISSUE THREAD

**Issue by lutricav** [mlhim/specs#82]
http://mlhim-specifications.readthedocs.org/en/2_5_0/front.html#mlhim-user-reference-manual
Purpose & Scope, paragraph 2:
“focused” instead of “limited” scope
Conformance:
A LIS is “a” formal document
Compliance:
Period at the end.
Availability:
Why allowing the download of the 2.5.0 development version and not the 2.4.7 stable version first?

http://mlhim-specifications.readthedocs.org/en/2_5_0/governance.html
Governance, paragraph 3:
There are two ` symbols around Google Plus and the link
Paragraph 4:
No links for MLHIM_governance_model.pdf

http://mlhim-specifications.readthedocs.org/en/2_5_0/executive_summary.html
Executive Summary:
Einsten’s quote is repeated. I would suggest this one:
For every complex problem there is an answer that is clear, simple, and wrong. (H. L. Mencken)

**Comment by twcook** [comment]
Thanks for these comments.  All were corrected. The reason for 2.5.0 download and not 2.4.7 is because these are the 2.5.0 docs.  Previous releases are available via the Releases link on GitHub.
